development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: doctalk_development
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432

 staging:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: doctalk_development
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432
